AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: 12
      DBInstanceIdentifier: crowfoundinfg
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      MasterUsername: dburitic
      MasterUserPassword: dburitic.001
      PubliclyAccessible: true
      VPCSecurityGroups: []
      BackupRetentionPeriod: 0
