apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowfounding-fronted-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: crowfounding-fronted-pod
  template:
    metadata:
      labels:
        app: crowfounding-fronted-app
        pod: crowfounding-fronted-pod
    spec:
      containers:
        - name: crowfounding-fronted-container
          image: dburitic/crowfoundinfg-fronted:latest
          resources:
            requests:
              memory: 500Mi
              cpu: 600m
            limits:
              memory: 500Mi
              cpu: 600m
          ports:
            - containerPort: 80