apiVersion: v1
kind: Service
metadata:
  name: crowfounding-fronted-service
spec:
  type: LoadBalancer
  selector:
    app: crowfounding-fronted-app
    pod: crowfounding-fronted-pod
  ports:
    - name: container-port
      targetPort: 80
      port: 80